In [1]:
import pandas as pd

## 데이터 불러오기

In [2]:
df = pd.read_csv("./player_db.csv")
df

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,...,Stamina,Aggression,Jumping,Composure,GK_Diving,GK_Handling,GK_Kicking,GK_Reflexes,GK_Positioning,price
0,크리스티안 겐트너,20,LM,99,98\n97\n98\n97\n97\n99\n99\n99\n99\n99\n98\n99...,"특성\n유리몸, 슬라이딩 태클 선호",1985.08.14 (38세),189cm,81kg,보통,...,109,96,90,96,12,10,23,22,27,"38,600,000 BP"
1,하비 가르시아,18,CDM,95,88\n86\n88\n86\n88\n88\n92\n88\n95\n91\n95\n91...,특성\n파워 헤더,1987.02.08 (36세),185cm,80kg,보통,...,105,106,105,94,9,14,24,11,18,"13,500,000 BP"
2,요렌테,21,ST,101,101\n93\n97\n93\n93\n91\n85\n91\n71\n69\n68\n6...,특성\n파워 헤더,1985.02.26 (38세),195cm,90kg,보통,...,90,103,94,100,14,23,26,9,13,"63,800,000 BP"
3,무사 뎀벨레,20,CF,98,97\n97\n98\n97\n97\n97\n93\n97\n86\n86\n82\n86...,"특성\n화려한 개인기, 중거리 슛 선호, 테크니컬 드리블러",1987.07.16 (36세),185cm,78kg,보통,...,97,85,87,109,27,24,22,12,26,"19,100,000 BP"
4,K. 엘아흐마디,17,CM,95,87\n89\n90\n89\n92\n90\n95\n90\n95\n91\n91\n91...,특성\n중거리 슛 선호,1985.01.27 (38세),179cm,78kg,보통,...,94,100,86,93,14,17,20,13,25,"8,740,000 BP"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59999,A. 크나우프,13,RM,84,79\n85\n83\n85\n83\n84\n79\n84\n72\n76\n67\n76...,특성\n스피드 드리블러,2002.01.10 (21세),180cm,73kg,마름,...,83,67,75,76,26,30,30,25,31,"2,830,000 BP"
60000,K. 야키치,14,CDM,83,75\n73\n75\n73\n76\n75\n79\n75\n83\n79\n82\n79...,특성,1997.05.14 (26세),181cm,75kg,보통,...,93,93,74,79,25,25,21,25,25,"3,560,000 BP"
60001,M. 구스토,12,RB,83,74\n79\n77\n79\n78\n81\n78\n81\n80\n83\n78\n83...,"특성\n슬라이딩 태클 선호, 스피드 드리블러",2003.05.19 (20세),179cm,74kg,마름,...,91,84,79,83,27,24,31,28,26,"3,700,000 BP"
60002,G. 마마르다슈빌리,12,GK,85,41\n37\n39\n37\n37\n39\n37\n39\n36\n37\n37\n37...,특성\nGK 적극적 크로스 수비,2000.09.29 (23세),199cm,88kg,마름,...,58,40,65,41,88,87,83,88,89,"3,740,000 BP"
60003,반데르송,13,RM,83,79\n83\n81\n83\n82\n83\n81\n83\n80\n82\n79\n82...,"특성\n얼리 크로스 선호, 테크니컬 드리블러",2001.06.21 (22세),180cm,74kg,마름,...,84,81,67,82,25,25,23,24,23,"3,390,000 BP"

In [3]:
player = pd.read_csv("./player.csv")
player

          id   play_name
0          0     데이비드 시먼
1          1      앨런 시어러
2          2      로비 파울러
3          3        로이 킨
4          4      라이언 긱스
...      ...         ...
59046  59046     A. 크나우프
59047  59047      K. 야키치
59048  59048      M. 구스토
59049  59049  G. 마마르다슈빌리
59050  59050        반데르송

[59051 rows x 2 columns]

In [4]:
df[df.name == '데이비드 시먼']

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,...,Stamina,Aggression,Jumping,Composure,GK_Diving,GK_Handling,GK_Kicking,GK_Reflexes,GK_Positioning,price
388,데이비드 시먼,19,GK,101,52\n55\n55\n55\n57\n57\n57\n57\n55\n54\n51\n54...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,68,48,77,86,97,106,104,101,103,"71,800,000 BP"
608,데이비드 시먼,19,GK,102,49\n52\n51\n52\n54\n54\n55\n54\n53\n52\n49\n52...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,69,52,79,83,98,104,105,103,105,"89,800,000 BP"
2828,데이비드 시먼,20,GK,104,55\n57\n57\n57\n59\n59\n60\n59\n57\n56\n53\n56...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,73,54,80,89,101,108,109,104,106,"800,000,000 BP"
2949,데이비드 시먼,15,GK,86,38\n39\n40\n39\n42\n41\n43\n41\n40\n39\n37\n39...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),191cm,93kg,보통,...,62,31,58,71,79,91,94,86,89,"5,030,000 BP"
3797,데이비드 시먼,13,GK,86,41\n41\n42\n41\n44\n44\n45\n44\n42\n41\n39\n41...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),191cm,93kg,보통,...,65,34,61,74,84,89,90,86,87,"4,460,000 BP"
4963,데이비드 시먼,16,GK,95,41\n42\n42\n42\n45\n44\n45\n44\n42\n41\n39\n41...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),191cm,93kg,보통,...,64,38,60,73,93,98,99,95,96,"18,100,000 BP"
6938,데이비드 시먼,15,GK,92,29\n28\n28\n28\n28\n29\n27\n29\n27\n27\n27\n27...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,36,33,60,85,85,97,97,97,94,"13,200,000 BP"

In [66]:
dfip = pd.read_csv("./data_plus_1.csv")
dfip

,name,pay_side,overall,Sprint_speed,Acceleration,Strength,Stamina,season,club_career
0,슈테펜 호프만,5,62,39,51,59,38,17,[]
1,J. 피에라치,5,60,59,55,68,66,18,[]
2,누어 허신,5,55,56,61,55,66,19,[]
3,마오하오위,5,49,69,60,35,49,20,[]
4,마이크 고메스,5,57,65,61,67,70,19,[]
...,...,...,...,...,...,...,...,...,...
50927,폴 란,6,66,51,56,68,65,20,[]
50928,크리스,5,62,50,44,59,59,18,"['2022 ~ 2022 / 발렌시아 CF', '임대 / AD 알코르콘']"
50929,루이스미,5,63,56,54,70,67,LIVE,[]
50930,시스코,5,63,51,50,78,64,18,"['2013 ~ 2018 / 볼로냐', '2015 ~ 2017 / 로마 FC', '..."
50931,리파,5,62,70,69,64,72,18,"['2020 ~ 2022 / 오모니아 니코시아', '2019 ~ 2020 / AEK..."

## 전처리

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60004 entries, 0 to 60003
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   name                   60004 non-null  object
 1   pay_side               60004 non-null  int64
 2   position               60004 non-null  object
 3   overall                60004 non-null  int64
 4   pomation               60004 non-null  object
 5   skill_swap             60004 non-null  object
 6   etc_birth              60004 non-null  object
 7   etc_height             60004 non-null  object
 8   etc_weight             60004 non-null  object
 9   etc_physical           60004 non-null  object
 10  etc_skill              60004 non-null  object
 11  etc_foot               60004 non-null  object
 12  etc_nation             60001 non-null  object
 13  Sprint_speed           60004 non-null  int64
 14  Acceleration           60004 non-null  int64
 15  Finishing              60004 non-null  int64
 16  Shot_power             60004 non-null  int64
 17  Long_shots             60004 non-null  int64
 18  Positioning            60004 non-null  int64
 19  Volleys                60004 non-null  int64
 20  Penalties              60004 non-null  int64
 21  Short_pass             60004 non-null  int64
 22  Eyesight               60004 non-null  int64
 23  Crossing               60004 non-null  int64
 24  Long_pass              60004 non-null  int64
 25  FK_Acc                 60004 non-null  int64
 26  Curve                  60004 non-null  int64
 27  Dribbling              60004 non-null  int64
 28  Ball_control           60004 non-null  int64
 29  Agility                60004 non-null  int64
 30  Balance                60004 non-null  int64
 31  Reflexes               60004 non-null  int64
 32  Interpersonal_defense  60004 non-null  int64
 33  Stand_tackle           60004 non-null  int64
 34  Interception           60004 non-null  int64
 35  Heading                60004 non-null  int64
 36  Slide_tackle           60004 non-null  object
 37  Strength               60004 non-null  int64
 38  Stamina                60004 non-null  int64
 39  Aggression             60004 non-null  int64
 40  Jumping                60004 non-null  int64
 41  Composure              60004 non-null  int64
 42  GK_Diving              60004 non-null  int64
 43  GK_Handling            60004 non-null  int64
 44  GK_Kicking             60004 non-null  int64
 45  GK_Reflexes            60004 non-null  int64
 46  GK_Positioning         60004 non-null  int64
 47  price                  60004 non-null  object
dtypes: int64(35), object(13)
memory usage: 22.0+ MB

In [26]:
test_df = df.drop_duplicates()

In [27]:
test_df[test_df.name == '데이비드 시먼']

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,...,Stamina,Aggression,Jumping,Composure,GK_Diving,GK_Handling,GK_Kicking,GK_Reflexes,GK_Positioning,price
388,데이비드 시먼,19,GK,101,52\n55\n55\n55\n57\n57\n57\n57\n55\n54\n51\n54...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,68,48,77,86,97,106,104,101,103,"71,800,000 BP"
608,데이비드 시먼,19,GK,102,49\n52\n51\n52\n54\n54\n55\n54\n53\n52\n49\n52...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,69,52,79,83,98,104,105,103,105,"89,800,000 BP"
2828,데이비드 시먼,20,GK,104,55\n57\n57\n57\n59\n59\n60\n59\n57\n56\n53\n56...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,73,54,80,89,101,108,109,104,106,"800,000,000 BP"
2949,데이비드 시먼,15,GK,86,38\n39\n40\n39\n42\n41\n43\n41\n40\n39\n37\n39...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),191cm,93kg,보통,...,62,31,58,71,79,91,94,86,89,"5,030,000 BP"
3797,데이비드 시먼,13,GK,86,41\n41\n42\n41\n44\n44\n45\n44\n42\n41\n39\n41...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),191cm,93kg,보통,...,65,34,61,74,84,89,90,86,87,"4,460,000 BP"
4963,데이비드 시먼,16,GK,95,41\n42\n42\n42\n45\n44\n45\n44\n42\n41\n39\n41...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),191cm,93kg,보통,...,64,38,60,73,93,98,99,95,96,"18,100,000 BP"
6938,데이비드 시먼,15,GK,92,29\n28\n28\n28\n28\n29\n27\n29\n27\n27\n27\n27...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,36,33,60,85,85,97,97,97,94,"13,200,000 BP"

In [25]:
player

          id   play_name
0          0     데이비드 시먼
1          1      앨런 시어러
2          2      로비 파울러
3          3        로이 킨
4          4      라이언 긱스
...      ...         ...
59046  59046     A. 크나우프
59047  59047      K. 야키치
59048  59048      M. 구스토
59049  59049  G. 마마르다슈빌리
59050  59050        반데르송

[59051 rows x 2 columns]

In [41]:
dfip = dfip[['name', 'pay_side', 'overall', 'Sprint_speed', 'season']]

In [72]:
test_2 = pd.merge(left=df, right=dfip, how='left', \
                  on=['name', 'pay_side', 'overall'], sort=False)
test_2

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,...,GK_Kicking,GK_Reflexes,GK_Positioning,price,Sprint_speed_y,Acceleration_y,Strength_y,Stamina_y,season,club_career
0,크리스티안 겐트너,20,LM,99,98\n97\n98\n97\n97\n99\n99\n99\n99\n99\n98\n99...,"특성\n유리몸, 슬라이딩 태클 선호",1985.08.14 (38세),189cm,81kg,보통,...,23,22,27,"38,600,000 BP",97.0,86.0,102.0,109.0,UP,"['2019 ~ 2021 / FC 루체른', '2010 ~ 2019 / 1. FC ..."
1,하비 가르시아,18,CDM,95,88\n86\n88\n86\n88\n88\n92\n88\n95\n91\n95\n91...,특성\n파워 헤더,1987.02.08 (36세),185cm,80kg,보통,...,24,11,18,"13,500,000 BP",86.0,83.0,97.0,105.0,UP,"['2017 ~ 2020 / 보아비스타', '2014 ~ 2017 / 레알 베티스'..."
2,요렌테,21,ST,101,101\n93\n97\n93\n93\n91\n85\n91\n71\n69\n68\n6...,특성\n파워 헤더,1985.02.26 (38세),195cm,90kg,보통,...,26,9,13,"63,800,000 BP",87.0,87.0,109.0,90.0,UP,"['2021 ~ 2021 / SD 에이바르', '2019 ~ 2021 / 우디네세'..."
3,무사 뎀벨레,20,CF,98,97\n97\n98\n97\n97\n97\n93\n97\n86\n86\n82\n86...,"특성\n화려한 개인기, 중거리 슛 선호, 테크니컬 드리블러",1987.07.16 (36세),185cm,78kg,보통,...,22,12,26,"19,100,000 BP",100.0,98.0,101.0,97.0,UP,"['2012 ~ 2019 / 광저우 시티', '2010 ~ 2012 / 토트넘 홋스..."
4,K. 엘아흐마디,17,CM,95,87\n89\n90\n89\n92\n90\n95\n90\n95\n91\n91\n91...,특성\n중거리 슛 선호,1985.01.27 (38세),179cm,78kg,보통,...,20,13,25,"8,740,000 BP",81.0,86.0,91.0,94.0,UP,"['2014 ~ 2018 / 알이티하드', '2012 ~ 2014 / 페예노르트',..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64937,A. 크나우프,13,RM,84,79\n85\n83\n85\n83\n84\n79\n84\n72\n76\n67\n76...,특성\n스피드 드리블러,2002.01.10 (21세),180cm,73kg,마름,...,30,25,31,"2,830,000 BP",NaN,NaN,NaN,NaN,NaN,NaN
64938,K. 야키치,14,CDM,83,75\n73\n75\n73\n76\n75\n79\n75\n83\n79\n82\n79...,특성,1997.05.14 (26세),181cm,75kg,보통,...,21,25,25,"3,560,000 BP",NaN,NaN,NaN,NaN,NaN,NaN
64939,M. 구스토,12,RB,83,74\n79\n77\n79\n78\n81\n78\n81\n80\n83\n78\n83...,"특성\n슬라이딩 태클 선호, 스피드 드리블러",2003.05.19 (20세),179cm,74kg,마름,...,31,28,26,"3,700,000 BP",NaN,NaN,NaN,NaN,NaN,NaN
64940,G. 마마르다슈빌리,12,GK,85,41\n37\n39\n37\n37\n39\n37\n39\n36\n37\n37\n37...,특성\nGK 적극적 크로스 수비,2000.09.29 (23세),199cm,88kg,마름,...,83,88,89,"3,740,000 BP",60.0,60.0,83.0,58.0,22PLA,"['2018 ~ 2022 / 발렌시아 CF', '2021 ~ 2021 / 디나모 트..."
64941,반데르송,13,RM,83,79\n83\n81\n83\n82\n83\n81\n83\n80\n82\n79\n82...,"특성\n얼리 크로스 선호, 테크니컬 드리블러",2001.06.21 (22세),180cm,74kg,마름,...,23,24,23,"3,390,000 BP",87.0,88.0,77.0,84.0,22PLA,['2021 ~ 2022 / AS 모나코']

In [73]:
test_2[test_2.name == '데이비드 시먼']

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,...,GK_Kicking,GK_Reflexes,GK_Positioning,price,Sprint_speed_y,Acceleration_y,Strength_y,Stamina_y,season,club_career
463,데이비드 시먼,19,GK,101,52\n55\n55\n55\n57\n57\n57\n57\n55\n54\n51\n54...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,104,101,103,"71,800,000 BP",54.0,70.0,86.0,68.0,EBS,"['1990 ~ 2003 / 맨체스터 시티', '1986 ~ 1990 / 아스널',..."
726,데이비드 시먼,19,GK,102,49\n52\n51\n52\n54\n54\n55\n54\n53\n52\n49\n52...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,105,103,105,"89,800,000 BP",51.0,71.0,81.0,69.0,CAP,"['1990 ~ 2003 / 맨체스터 시티', '1986 ~ 1990 / 아스널',..."
3380,데이비드 시먼,20,GK,104,55\n57\n57\n57\n59\n59\n60\n59\n57\n56\n53\n56...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,109,104,106,"800,000,000 BP",57.0,73.0,85.0,73.0,ICON,"['1990 ~ 2003 / 맨체스터 시티', '1986 ~ 1990 / 아스널',..."
3512,데이비드 시먼,15,GK,86,38\n39\n40\n39\n42\n41\n43\n41\n40\n39\n37\n39...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),191cm,93kg,보통,...,94,86,89,"5,030,000 BP",55.0,51.0,81.0,62.0,NHD,"['1990 ~ 2003 / 맨체스터 시티', '1986 ~ 1990 / 아스널',..."
4475,데이비드 시먼,13,GK,86,41\n41\n42\n41\n44\n44\n45\n44\n42\n41\n39\n41...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),191cm,93kg,보통,...,90,86,87,"4,460,000 BP",58.0,54.0,84.0,65.0,TT,"['1990 ~ 2003 / 맨체스터 시티', '1986 ~ 1990 / 아스널',..."
5827,데이비드 시먼,16,GK,95,41\n42\n42\n42\n45\n44\n45\n44\n42\n41\n39\n41...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),191cm,93kg,보통,...,99,95,96,"18,100,000 BP",57.0,59.0,83.0,64.0,HOT,"['1990 ~ 2003 / 맨체스터 시티', '1986 ~ 1990 / 아스널',..."
8022,데이비드 시먼,15,GK,92,29\n28\n28\n28\n28\n29\n27\n29\n27\n27\n27\n27...,"특성\nGK 능숙한 펀칭, GK 멀리 던지기",1963.09.19 (60세),193cm,93kg,보통,...,97,97,94,"13,200,000 BP",57.0,55.0,85.0,36.0,LH,"['1990 ~ 2003 / 맨체스터 시티', '1986 ~ 1990 / 아스널',..."

In [75]:
test_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 64942 entries, 0 to 64941
Data columns (total 54 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   name                   64942 non-null  object
 1   pay_side               64942 non-null  int64
 2   position               64942 non-null  object
 3   overall                64942 non-null  int64
 4   pomation               64942 non-null  object
 5   skill_swap             64942 non-null  object
 6   etc_birth              64942 non-null  object
 7   etc_height             64942 non-null  object
 8   etc_weight             64942 non-null  object
 9   etc_physical           64942 non-null  object
 10  etc_skill              64942 non-null  object
 11  etc_foot               64942 non-null  object
 12  etc_nation             64939 non-null  object
 13  Sprint_speed_x         64942 non-null  int64
 14  Acceleration_x         64942 non-null  int64
 15  Finishing              64942 non-null  int64
 16  Shot_power             64942 non-null  int64
 17  Long_shots             64942 non-null  int64
 18  Positioning            64942 non-null  int64
 19  Volleys                64942 non-null  int64
 20  Penalties              64942 non-null  int64
 21  Short_pass             64942 non-null  int64
 22  Eyesight               64942 non-null  int64
 23  Crossing               64942 non-null  int64
 24  Long_pass              64942 non-null  int64
 25  FK_Acc                 64942 non-null  int64
 26  Curve                  64942 non-null  int64
 27  Dribbling              64942 non-null  int64
 28  Ball_control           64942 non-null  int64
 29  Agility                64942 non-null  int64
 30  Balance                64942 non-null  int64
 31  Reflexes               64942 non-null  int64
 32  Interpersonal_defense  64942 non-null  int64
 33  Stand_tackle           64942 non-null  int64
 34  Interception           64942 non-null  int64
 35  Heading                64942 non-null  int64
 36  Slide_tackle           64942 non-null  object
 37  Strength_x             64942 non-null  int64
 38  Stamina_x              64942 non-null  int64
 39  Aggression             64942 non-null  int64
 40  Jumping                64942 non-null  int64
 41  Composure              64942 non-null  int64
 42  GK_Diving              64942 non-null  int64
 43  GK_Handling            64942 non-null  int64
 44  GK_Kicking             64942 non-null  int64
 45  GK_Reflexes            64942 non-null  int64
 46  GK_Positioning         64942 non-null  int64
 47  price                  64942 non-null  object
 48  Sprint_speed_y         52348 non-null  float64
 49  Acceleration_y         52348 non-null  float64
 50  Strength_y             52348 non-null  float64
 51  Stamina_y              52348 non-null  float64
 52  season                 52348 non-null  object
 53  club_career            52348 non-null  object
dtypes: float64(4), int64(35), object(15)
memory usage: 27.3+ MB

In [76]:
test_2.drop_duplicates()

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,...,GK_Kicking,GK_Reflexes,GK_Positioning,price,Sprint_speed_y,Acceleration_y,Strength_y,Stamina_y,season,club_career
0,크리스티안 겐트너,20,LM,99,98\n97\n98\n97\n97\n99\n99\n99\n99\n99\n98\n99...,"특성\n유리몸, 슬라이딩 태클 선호",1985.08.14 (38세),189cm,81kg,보통,...,23,22,27,"38,600,000 BP",97.0,86.0,102.0,109.0,UP,"['2019 ~ 2021 / FC 루체른', '2010 ~ 2019 / 1. FC ..."
1,하비 가르시아,18,CDM,95,88\n86\n88\n86\n88\n88\n92\n88\n95\n91\n95\n91...,특성\n파워 헤더,1987.02.08 (36세),185cm,80kg,보통,...,24,11,18,"13,500,000 BP",86.0,83.0,97.0,105.0,UP,"['2017 ~ 2020 / 보아비스타', '2014 ~ 2017 / 레알 베티스'..."
2,요렌테,21,ST,101,101\n93\n97\n93\n93\n91\n85\n91\n71\n69\n68\n6...,특성\n파워 헤더,1985.02.26 (38세),195cm,90kg,보통,...,26,9,13,"63,800,000 BP",87.0,87.0,109.0,90.0,UP,"['2021 ~ 2021 / SD 에이바르', '2019 ~ 2021 / 우디네세'..."
3,무사 뎀벨레,20,CF,98,97\n97\n98\n97\n97\n97\n93\n97\n86\n86\n82\n86...,"특성\n화려한 개인기, 중거리 슛 선호, 테크니컬 드리블러",1987.07.16 (36세),185cm,78kg,보통,...,22,12,26,"19,100,000 BP",100.0,98.0,101.0,97.0,UP,"['2012 ~ 2019 / 광저우 시티', '2010 ~ 2012 / 토트넘 홋스..."
4,K. 엘아흐마디,17,CM,95,87\n89\n90\n89\n92\n90\n95\n90\n95\n91\n91\n91...,특성\n중거리 슛 선호,1985.01.27 (38세),179cm,78kg,보통,...,20,13,25,"8,740,000 BP",81.0,86.0,91.0,94.0,UP,"['2014 ~ 2018 / 알이티하드', '2012 ~ 2014 / 페예노르트',..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64937,A. 크나우프,13,RM,84,79\n85\n83\n85\n83\n84\n79\n84\n72\n76\n67\n76...,특성\n스피드 드리블러,2002.01.10 (21세),180cm,73kg,마름,...,30,25,31,"2,830,000 BP",NaN,NaN,NaN,NaN,NaN,NaN
64938,K. 야키치,14,CDM,83,75\n73\n75\n73\n76\n75\n79\n75\n83\n79\n82\n79...,특성,1997.05.14 (26세),181cm,75kg,보통,...,21,25,25,"3,560,000 BP",NaN,NaN,NaN,NaN,NaN,NaN
64939,M. 구스토,12,RB,83,74\n79\n77\n79\n78\n81\n78\n81\n80\n83\n78\n83...,"특성\n슬라이딩 태클 선호, 스피드 드리블러",2003.05.19 (20세),179cm,74kg,마름,...,31,28,26,"3,700,000 BP",NaN,NaN,NaN,NaN,NaN,NaN
64940,G. 마마르다슈빌리,12,GK,85,41\n37\n39\n37\n37\n39\n37\n39\n36\n37\n37\n37...,특성\nGK 적극적 크로스 수비,2000.09.29 (23세),199cm,88kg,마름,...,83,88,89,"3,740,000 BP",60.0,60.0,83.0,58.0,22PLA,"['2018 ~ 2022 / 발렌시아 CF', '2021 ~ 2021 / 디나모 트..."
64941,반데르송,13,RM,83,79\n83\n81\n83\n82\n83\n81\n83\n80\n82\n79\n82...,"특성\n얼리 크로스 선호, 테크니컬 드리블러",2001.06.21 (22세),180cm,74kg,마름,...,23,24,23,"3,390,000 BP",87.0,88.0,77.0,84.0,22PLA,['2021 ~ 2022 / AS 모나코']

In [80]:
test = test_2.drop(['Sprint_speed_y', 'Acceleration_y', 'Strength_y', 'Stamina_y'], axis=1)

In [82]:
test.club_career[0]

"['2019 ~ 2021 / FC 루체른', '2010 ~ 2019 / 1. FC 우니온 베를린', '2008 ~ 2010 / VfB 슈투트가르트', '2005 ~ 2008 / VfL 볼프스부르크', '2007 ~ 2008 / VfB 슈투트가르트', '임대 / VfL 볼프스부르크']"

In [84]:
test.pomation[0]

'98\n97\n98\n97\n97\n99\n99\n99\n99\n99\n98\n99\n98\n97\n98\n27'

In [87]:
test.skill_swap[0]

'특성\n유리몸, 슬라이딩 태클 선호'

In [62]:


dfip.overall.apply(split('\n'))

NameError: name 'split' is not defined

In [64]:
dfip['overall']=dfip['overall'].astype(int)

ValueError: invalid literal for int() with base 10: '60\n(59)'

In [38]:
for i in dfip.overall:
    print(i)

AttributeError: 'NoneType' object has no attribute 'overall'

In [10]:
test = test[['name', 'price', 'pay_side_y', 'overall_y', 'season']]
test.drop_duplicates()[test.drop_duplicates().name == '데이비드 시먼']

          name           price  pay_side_y overall_y season
1303   데이비드 시먼   71,800,000 BP          19       101    EBS
1862   데이비드 시먼   89,800,000 BP          19       102    CAP
7316   데이비드 시먼  800,000,000 BP          20       104   ICON
7317   데이비드 시먼  800,000,000 BP          16        95    HOT
7318   데이비드 시먼  800,000,000 BP          15        92     LH
7319   데이비드 시먼   18,100,000 BP          20       104   ICON
7320   데이비드 시먼   18,100,000 BP          16        95    HOT
7321   데이비드 시먼   18,100,000 BP          15        92     LH
7322   데이비드 시먼   13,200,000 BP          20       104   ICON
7323   데이비드 시먼   13,200,000 BP          16        95    HOT
7324   데이비드 시먼   13,200,000 BP          15        92     LH
7525   데이비드 시먼    5,030,000 BP          15        86    NHD
11104  데이비드 시먼    4,460,000 BP          13        86     TT